// Pre-populated exercise library
export const seedExercises = [
  // CHEST
  {
    name: "Barbell Bench Press",
    description: "Classic compound chest exercise using a barbell",
    instructions: "Lie on a flat bench, grip the barbell slightly wider than shoulder-width, lower to chest, press up.",
    category: "strength",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
  },
  {
    name: "Incline Dumbbell Press",
    description: "Upper chest focused pressing movement",
    instructions: "Set bench to 30-45 degrees, press dumbbells from shoulder level to full extension.",
    category: "strength",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "intermediate",
  },
  {
    name: "Push-ups",
    description: "Bodyweight chest and tricep exercise",
    instructions: "Start in plank position, lower chest to floor, push back up while maintaining straight body.",
    category: "strength",
    muscleGroups: ["chest", "triceps", "shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
  },
  {
    name: "Dumbbell Flyes",
    description: "Isolation exercise for chest stretch and contraction",
    instructions: "Lie on bench with dumbbells extended above chest, lower with slight elbow bend in arc motion.",
    category: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "bench"],
    difficulty: "intermediate",
  },
  {
    name: "Cable Crossover",
    description: "Cable machine chest isolation",
    instructions: "Stand between cable stations, bring handles together in front of chest in hugging motion.",
    category: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
  },

  // BACK
  {
    name: "Deadlift",
    description: "Fundamental compound lift for posterior chain",
    instructions: "Stand with feet hip-width, grip barbell, drive through heels while keeping back straight.",
    category: "strength",
    muscleGroups: ["back", "hamstrings", "glutes", "core"],
    equipment: ["barbell"],
    difficulty: "advanced",
  },
  {
    name: "Pull-ups",
    description: "Bodyweight vertical pulling exercise",
    instructions: "Hang from bar with overhand grip, pull until chin clears bar, lower with control.",
    category: "strength",
    muscleGroups: ["back", "biceps", "core"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
  },
  {
    name: "Barbell Row",
    description: "Bent over rowing movement for back thickness",
    instructions: "Hinge at hips, row barbell to lower chest while keeping back flat.",
    category: "strength",
    muscleGroups: ["back", "biceps", "rear delts"],
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    name: "Lat Pulldown",
    description: "Machine-based vertical pull",
    instructions: "Sit at lat pulldown machine, pull bar to upper chest, squeeze lats at bottom.",
    category: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["cable machine"],
    difficulty: "beginner",
  },
  {
    name: "Seated Cable Row",
    description: "Horizontal pulling for mid-back",
    instructions: "Sit at cable row station, pull handle to lower chest, squeeze shoulder blades.",
    category: "strength",
    muscleGroups: ["back", "biceps", "rear delts"],
    equipment: ["cable machine"],
    difficulty: "beginner",
  },

  // SHOULDERS
  {
    name: "Overhead Press",
    description: "Standing barbell press for shoulder development",
    instructions: "Press barbell from shoulders to overhead while bracing core, lower with control.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    name: "Dumbbell Lateral Raise",
    description: "Isolation for side deltoids",
    instructions: "Raise dumbbells to sides until arms parallel to floor, lower with control.",
    category: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
  },
  {
    name: "Face Pulls",
    description: "Rear delt and rotator cuff exercise",
    instructions: "Pull rope attachment to face level, spreading hands apart at end of movement.",
    category: "strength",
    muscleGroups: ["shoulders", "upper back"],
    equipment: ["cable machine", "rope attachment"],
    difficulty: "beginner",
  },
  {
    name: "Arnold Press",
    description: "Rotating dumbbell press for complete shoulder development",
    instructions: "Start with dumbbells at shoulders palms facing you, rotate and press overhead.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
  },

  // LEGS
  {
    name: "Barbell Back Squat",
    description: "King of leg exercises for overall lower body development",
    instructions: "Bar on upper back, squat to parallel or below, drive through heels to stand.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "hamstrings", "core"],
    equipment: ["barbell", "squat rack"],
    difficulty: "intermediate",
  },
  {
    name: "Front Squat",
    description: "Quad-dominant squat variation",
    instructions: "Hold barbell at front of shoulders, squat while keeping torso upright.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "core"],
    equipment: ["barbell", "squat rack"],
    difficulty: "advanced",
  },
  {
    name: "Romanian Deadlift",
    description: "Hip hinge for hamstrings and glutes",
    instructions: "Hinge at hips with slight knee bend, lower weight along legs, feel hamstring stretch.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    name: "Leg Press",
    description: "Machine-based leg pressing movement",
    instructions: "Sit in leg press machine, lower weight until knees at 90 degrees, press back up.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    equipment: ["leg press machine"],
    difficulty: "beginner",
  },
  {
    name: "Walking Lunges",
    description: "Unilateral leg exercise for balance and strength",
    instructions: "Step forward into lunge, alternate legs while walking forward.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: "beginner",
  },
  {
    name: "Leg Curl",
    description: "Isolation for hamstrings",
    instructions: "Lie face down on machine, curl weight by bending knees.",
    category: "strength",
    muscleGroups: ["hamstrings"],
    equipment: ["leg curl machine"],
    difficulty: "beginner",
  },
  {
    name: "Leg Extension",
    description: "Isolation for quadriceps",
    instructions: "Sit in machine, extend legs until straight, lower with control.",
    category: "strength",
    muscleGroups: ["quadriceps"],
    equipment: ["leg extension machine"],
    difficulty: "beginner",
  },
  {
    name: "Calf Raises",
    description: "Standing calf exercise",
    instructions: "Rise onto toes, hold at top, lower heels below platform level.",
    category: "strength",
    muscleGroups: ["calves"],
    equipment: ["calf raise machine", "bodyweight"],
    difficulty: "beginner",
  },

  // ARMS
  {
    name: "Barbell Curl",
    description: "Classic bicep exercise",
    instructions: "Stand with barbell, curl weight while keeping elbows at sides.",
    category: "strength",
    muscleGroups: ["biceps"],
    equipment: ["barbell"],
    difficulty: "beginner",
  },
  {
    name: "Hammer Curls",
    description: "Neutral grip curl for biceps and forearms",
    instructions: "Curl dumbbells with palms facing each other throughout movement.",
    category: "strength",
    muscleGroups: ["biceps", "forearms"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
  },
  {
    name: "Tricep Pushdown",
    description: "Cable exercise for triceps",
    instructions: "Push cable attachment down by extending elbows, keep upper arms stationary.",
    category: "strength",
    muscleGroups: ["triceps"],
    equipment: ["cable machine"],
    difficulty: "beginner",
  },
  {
    name: "Skull Crushers",
    description: "Lying tricep extension",
    instructions: "Lie on bench, lower weight to forehead by bending elbows, extend back up.",
    category: "strength",
    muscleGroups: ["triceps"],
    equipment: ["barbell", "ez-bar", "bench"],
    difficulty: "intermediate",
  },
  {
    name: "Dips",
    description: "Compound movement for triceps and chest",
    instructions: "Support yourself on parallel bars, lower until upper arms parallel to floor, push back up.",
    category: "strength",
    muscleGroups: ["triceps", "chest", "shoulders"],
    equipment: ["dip station"],
    difficulty: "intermediate",
  },

  // CORE
  {
    name: "Plank",
    description: "Isometric core stabilization",
    instructions: "Hold push-up position on forearms, maintain straight line from head to heels.",
    category: "strength",
    muscleGroups: ["core", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
  },
  {
    name: "Hanging Leg Raise",
    description: "Advanced ab exercise",
    instructions: "Hang from bar, raise legs to parallel or above, lower with control.",
    category: "strength",
    muscleGroups: ["core", "hip flexors"],
    equipment: ["pull-up bar"],
    difficulty: "advanced",
  },
  {
    name: "Cable Crunch",
    description: "Weighted ab exercise",
    instructions: "Kneel at cable machine, crunch down by contracting abs.",
    category: "strength",
    muscleGroups: ["core"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
  },
  {
    name: "Russian Twist",
    description: "Rotational core exercise",
    instructions: "Sit with knees bent, lean back slightly, rotate torso side to side.",
    category: "strength",
    muscleGroups: ["core", "obliques"],
    equipment: ["bodyweight", "medicine ball"],
    difficulty: "beginner",
  },
  {
    name: "Ab Wheel Rollout",
    description: "Anti-extension core exercise",
    instructions: "Kneel with ab wheel, roll forward maintaining tight core, roll back.",
    category: "strength",
    muscleGroups: ["core"],
    equipment: ["ab wheel"],
    difficulty: "intermediate",
  },

  // CARDIO
  {
    name: "Running",
    description: "Cardiovascular endurance training",
    instructions: "Maintain steady pace or intervals depending on goal.",
    category: "cardio",
    muscleGroups: ["cardiovascular", "legs"],
    equipment: ["treadmill", "outdoor"],
    difficulty: "beginner",
  },
  {
    name: "Cycling",
    description: "Low-impact cardiovascular exercise",
    instructions: "Maintain consistent cadence, adjust resistance as needed.",
    category: "cardio",
    muscleGroups: ["cardiovascular", "quadriceps"],
    equipment: ["stationary bike", "bicycle"],
    difficulty: "beginner",
  },
  {
    name: "Rowing",
    description: "Full body cardiovascular exercise",
    instructions: "Push with legs, pull with arms, maintain rhythm.",
    category: "cardio",
    muscleGroups: ["cardiovascular", "back", "legs"],
    equipment: ["rowing machine"],
    difficulty: "intermediate",
  },
  {
    name: "Jump Rope",
    description: "High-intensity cardio and coordination",
    instructions: "Jump over rope with each rotation, land softly on balls of feet.",
    category: "cardio",
    muscleGroups: ["cardiovascular", "calves"],
    equipment: ["jump rope"],
    difficulty: "intermediate",
  },
  {
    name: "Burpees",
    description: "Full body conditioning exercise",
    instructions: "Drop to push-up, perform push-up, jump feet to hands, jump up with arms overhead.",
    category: "cardio",
    muscleGroups: ["cardiovascular", "full body"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
  },
  {
    name: "Stair Climber",
    description: "Lower body cardio focus",
    instructions: "Step continuously on machine, adjust speed as needed.",
    category: "cardio",
    muscleGroups: ["cardiovascular", "glutes", "quadriceps"],
    equipment: ["stair climber machine"],
    difficulty: "beginner",
  },

  // TRACK & SPRINTS
  {
    name: "100m Sprint",
    description: "Maximum effort short distance",
    instructions: "Explosive start, maintain top speed, full effort throughout.",
    category: "sport",
    muscleGroups: ["cardiovascular", "quadriceps", "hamstrings", "glutes"],
    equipment: ["track", "outdoor"],
    difficulty: "advanced",
  },
  {
    name: "200m Sprint",
    description: "Speed endurance sprint",
    instructions: "Strong start, maintain speed around curve, finish strong.",
    category: "sport",
    muscleGroups: ["cardiovascular", "quadriceps", "hamstrings", "glutes"],
    equipment: ["track", "outdoor"],
    difficulty: "advanced",
  },
  {
    name: "400m Run",
    description: "Speed endurance race distance",
    instructions: "Controlled start, maintain pace, kick in final 100m.",
    category: "sport",
    muscleGroups: ["cardiovascular", "legs"],
    equipment: ["track", "outdoor"],
    difficulty: "advanced",
  },
  {
    name: "Hill Sprints",
    description: "Incline sprint training",
    instructions: "Sprint up hill at maximum effort, walk down for recovery.",
    category: "cardio",
    muscleGroups: ["cardiovascular", "glutes", "quadriceps", "calves"],
    equipment: ["outdoor", "treadmill"],
    difficulty: "advanced",
  },

  // FLEXIBILITY / MOBILITY
  {
    name: "Foam Rolling",
    description: "Self-myofascial release",
    instructions: "Roll slowly over tight muscles, pause on tender spots.",
    category: "flexibility",
    muscleGroups: ["full body"],
    equipment: ["foam roller"],
    difficulty: "beginner",
  },
  {
    name: "Hip Flexor Stretch",
    description: "Stretch for tight hip flexors",
    instructions: "Kneel in lunge position, push hips forward, hold stretch.",
    category: "flexibility",
    muscleGroups: ["hip flexors"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
  },
  {
    name: "Hamstring Stretch",
    description: "Flexibility for hamstrings",
    instructions: "Sit with leg extended, reach toward toes, hold stretch.",
    category: "flexibility",
    muscleGroups: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
  },
  {
    name: "Shoulder Dislocates",
    description: "Shoulder mobility exercise",
    instructions: "Hold band or stick wide, pass over head and behind back.",
    category: "flexibility",
    muscleGroups: ["shoulders"],
    equipment: ["resistance band", "pvc pipe"],
    difficulty: "beginner",
  },

  // SKILL / GYMNASTICS
  {
    name: "Back Tuck",
    description: "Backflip with tucked position",
    instructions: "Jump up, tuck knees to chest, rotate backwards, land on feet.",
    category: "skill",
    muscleGroups: ["core", "legs"],
    equipment: ["gymnastics mat", "spring floor"],
    difficulty: "advanced",
  },
  {
    name: "Handstand",
    description: "Inverted balance position",
    instructions: "Kick up to inverted position, stack shoulders over wrists, maintain balance.",
    category: "skill",
    muscleGroups: ["shoulders", "core"],
    equipment: ["bodyweight", "wall"],
    difficulty: "intermediate",
  },
  {
    name: "Muscle Up",
    description: "Pull-up transitioning to dip position",
    instructions: "Explosive pull-up, transition hands over bar, press to support.",
    category: "skill",
    muscleGroups: ["back", "chest", "triceps"],
    equipment: ["pull-up bar", "rings"],
    difficulty: "advanced",
  },
  {
    name: "Pistol Squat",
    description: "Single leg squat",
    instructions: "Squat on one leg with other extended forward, stand back up.",
    category: "skill",
    muscleGroups: ["quadriceps", "glutes", "core"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
  },
  {
    name: "L-Sit",
    description: "Isometric core and hip flexor hold",
    instructions: "Support body on hands with legs extended parallel to floor.",
    category: "skill",
    muscleGroups: ["core", "hip flexors", "triceps"],
    equipment: ["parallettes", "floor"],
    difficulty: "intermediate",
  },
];
